# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'IAPDemoProjectCourse' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for IAPDemoProjectCourse
  pod 'OpenSSL', :git => 'https://github.com/wzbozon/OpenSSL-Pod'

end
